class GhmcWard {
  final String code;
  final String name;
  final String circle; // GHMC circle/zone

  const GhmcWard({required this.code, required this.name, required this.circle});
}

const List<GhmcWard> ghmcWards = [
  // Charminar Circle
  GhmcWard(code: 'W001', name: 'Karwan', circle: 'Charminar'),
  GhmcWard(code: 'W002', name: 'Bahadurpura', circle: 'Charminar'),
  GhmcWard(code: 'W003', name: 'Santoshnagar', circle: 'Charminar'),
  GhmcWard(code: 'W004', name: 'Chandrayangutta', circle: 'Charminar'),
  GhmcWard(code: 'W005', name: 'Kishanbagh', circle: 'Charminar'),
  GhmcWard(code: 'W006', name: 'Champapet', circle: 'Charminar'),
  GhmcWard(code: 'W007', name: 'Saidabad', circle: 'Charminar'),
  GhmcWard(code: 'W008', name: 'Malakpet', circle: 'Charminar'),
  GhmcWard(code: 'W009', name: 'Nampally', circle: 'Charminar'),
  GhmcWard(code: 'W010', name: 'Goshamahal', circle: 'Charminar'),
  GhmcWard(code: 'W011', name: 'Charminar', circle: 'Charminar'),
  GhmcWard(code: 'W012', name: 'Yakutpura', circle: 'Charminar'),
  GhmcWard(code: 'W013', name: 'Falaknuma', circle: 'Charminar'),
  GhmcWard(code: 'W014', name: 'Mehdipatnam', circle: 'Charminar'),
  GhmcWard(code: 'W015', name: 'Rajendranagar', circle: 'Charminar'),
  // LB Nagar Circle
  GhmcWard(code: 'W016', name: 'LB Nagar', circle: 'LB Nagar'),
  GhmcWard(code: 'W017', name: 'Saroornagar', circle: 'LB Nagar'),
  GhmcWard(code: 'W018', name: 'Hayathnagar', circle: 'LB Nagar'),
  GhmcWard(code: 'W019', name: 'Vanasthalipuram', circle: 'LB Nagar'),
  GhmcWard(code: 'W020', name: 'Moosarambagh', circle: 'LB Nagar'),
  GhmcWard(code: 'W021', name: 'Dilsukhnagar', circle: 'LB Nagar'),
  GhmcWard(code: 'W022', name: 'Gaddiannaram', circle: 'LB Nagar'),
  GhmcWard(code: 'W023', name: 'Kothapet', circle: 'LB Nagar'),
  GhmcWard(code: 'W024', name: 'Amberpet', circle: 'LB Nagar'),
  GhmcWard(code: 'W025', name: 'Nacharam', circle: 'LB Nagar'),
  // Khairatabad Circle
  GhmcWard(code: 'W026', name: 'Khairatabad', circle: 'Khairatabad'),
  GhmcWard(code: 'W027', name: 'Panjagutta', circle: 'Khairatabad'),
  GhmcWard(code: 'W028', name: 'Jubilee Hills', circle: 'Khairatabad'),
  GhmcWard(code: 'W029', name: 'Film Nagar', circle: 'Khairatabad'),
  GhmcWard(code: 'W030', name: 'Banjara Hills', circle: 'Khairatabad'),
  GhmcWard(code: 'W031', name: 'Somajiguda', circle: 'Khairatabad'),
  GhmcWard(code: 'W032', name: 'Narayanguda', circle: 'Khairatabad'),
  GhmcWard(code: 'W033', name: 'Himayatnagar', circle: 'Khairatabad'),
  GhmcWard(code: 'W034', name: 'Asifnagar', circle: 'Khairatabad'),
  GhmcWard(code: 'W035', name: 'Tolichowki', circle: 'Khairatabad'),
  GhmcWard(code: 'W036', name: 'Manikonda', circle: 'Khairatabad'),
  GhmcWard(code: 'W037', name: 'Attapur', circle: 'Khairatabad'),
  GhmcWard(code: 'W038', name: 'Shaikpet', circle: 'Khairatabad'),
  GhmcWard(code: 'W039', name: 'Masab Tank', circle: 'Khairatabad'),
  GhmcWard(code: 'W040', name: 'Humayunnagar', circle: 'Khairatabad'),
  // Secunderabad Circle
  GhmcWard(code: 'W041', name: 'Secunderabad', circle: 'Secunderabad'),
  GhmcWard(code: 'W042', name: 'Marredpally', circle: 'Secunderabad'),
  GhmcWard(code: 'W043', name: 'Trimulgherry', circle: 'Secunderabad'),
  GhmcWard(code: 'W044', name: 'Malkajgiri', circle: 'Secunderabad'),
  GhmcWard(code: 'W045', name: 'Uppal', circle: 'Secunderabad'),
  GhmcWard(code: 'W046', name: 'Ghatkesar', circle: 'Secunderabad'),
  GhmcWard(code: 'W047', name: 'Neredmet', circle: 'Secunderabad'),
  GhmcWard(code: 'W048', name: 'AS Rao Nagar', circle: 'Secunderabad'),
  GhmcWard(code: 'W049', name: 'Ecil', circle: 'Secunderabad'),
  GhmcWard(code: 'W050', name: 'Kapra', circle: 'Secunderabad'),
  // Serilingampally Circle
  GhmcWard(code: 'W051', name: 'Serilingampally', circle: 'Serilingampally'),
  GhmcWard(code: 'W052', name: 'Kukatpally', circle: 'Serilingampally'),
  GhmcWard(code: 'W053', name: 'Miyapur', circle: 'Serilingampally'),
  GhmcWard(code: 'W054', name: 'Bachupally', circle: 'Serilingampally'),
  GhmcWard(code: 'W055', name: 'Quthbullapur', circle: 'Serilingampally'),
  GhmcWard(code: 'W056', name: 'Alwal', circle: 'Serilingampally'),
  GhmcWard(code: 'W057', name: 'Suraram', circle: 'Serilingampally'),
  GhmcWard(code: 'W058', name: 'Balanagar', circle: 'Serilingampally'),
  GhmcWard(code: 'W059', name: 'Moosapet', circle: 'Serilingampally'),
  GhmcWard(code: 'W060', name: 'Borabanda', circle: 'Serilingampally'),
  GhmcWard(code: 'W061', name: 'Nizampet', circle: 'Serilingampally'),
  GhmcWard(code: 'W062', name: 'Chanda Nagar', circle: 'Serilingampally'),
  GhmcWard(code: 'W063', name: 'Lingampally', circle: 'Serilingampally'),
  GhmcWard(code: 'W064', name: 'Tellapur', circle: 'Serilingampally'),
  GhmcWard(code: 'W065', name: 'Gachibowli', circle: 'Serilingampally'),
  GhmcWard(code: 'W066', name: 'Nanakramguda', circle: 'Serilingampally'),
  GhmcWard(code: 'W067', name: 'Hafeezpet', circle: 'Serilingampally'),
  GhmcWard(code: 'W068', name: 'Madhapur', circle: 'Serilingampally'),
  GhmcWard(code: 'W069', name: 'Kondapur', circle: 'Serilingampally'),
  GhmcWard(code: 'W070', name: 'Raidurg', circle: 'Serilingampally'),
  // Additional wards
  GhmcWard(code: 'W071', name: 'Begumpet', circle: 'Secunderabad'),
  GhmcWard(code: 'W072', name: 'Ameerpet', circle: 'Secunderabad'),
  GhmcWard(code: 'W073', name: 'SR Nagar', circle: 'Secunderabad'),
  GhmcWard(code: 'W074', name: 'Musheerabad', circle: 'Secunderabad'),
  GhmcWard(code: 'W075', name: 'Bowenpally', circle: 'Secunderabad'),
  GhmcWard(code: 'W076', name: 'Gandhinagar', circle: 'Secunderabad'),
  GhmcWard(code: 'W077', name: 'Chilkalguda', circle: 'Secunderabad'),
  GhmcWard(code: 'W078', name: 'Padmarao Nagar', circle: 'Secunderabad'),
  GhmcWard(code: 'W079', name: 'Jawahar Nagar', circle: 'Secunderabad'),
  GhmcWard(code: 'W080', name: 'Mettuguda', circle: 'Secunderabad'),
  GhmcWard(code: 'W081', name: 'Lalaguda', circle: 'Secunderabad'),
  GhmcWard(code: 'W082', name: 'Tilaknagar', circle: 'Secunderabad'),
  GhmcWard(code: 'W083', name: 'Kavadiguda', circle: 'Secunderabad'),
  GhmcWard(code: 'W084', name: 'Osmania University', circle: 'LB Nagar'),
  GhmcWard(code: 'W085', name: 'Tarnaka', circle: 'LB Nagar'),
  GhmcWard(code: 'W086', name: 'Maredpally', circle: 'Secunderabad'),
  GhmcWard(code: 'W087', name: 'Sitafalmandi', circle: 'Secunderabad'),
  GhmcWard(code: 'W088', name: 'Karkhana', circle: 'Secunderabad'),
  GhmcWard(code: 'W089', name: 'Safilguda', circle: 'Secunderabad'),
  GhmcWard(code: 'W090', name: 'Parsigutta', circle: 'Secunderabad'),
  GhmcWard(code: 'W091', name: 'Rein Bazaar', circle: 'Charminar'),
  GhmcWard(code: 'W092', name: 'Chudi Bazar', circle: 'Charminar'),
  GhmcWard(code: 'W093', name: 'Begum Bazaar', circle: 'Charminar'),
  GhmcWard(code: 'W094', name: 'Koti', circle: 'Charminar'),
  GhmcWard(code: 'W095', name: 'Abids', circle: 'Charminar'),
  GhmcWard(code: 'W096', name: 'Vidyanagar', circle: 'Charminar'),
  GhmcWard(code: 'W097', name: 'Himayatsagar', circle: 'Charminar'),
  GhmcWard(code: 'W098', name: 'Golconda', circle: 'Charminar'),
  GhmcWard(code: 'W099', name: 'Langar Houz', circle: 'Charminar'),
  GhmcWard(code: 'W100', name: 'Bandlaguda', circle: 'LB Nagar'),
  GhmcWard(code: 'W101', name: 'Nagole', circle: 'LB Nagar'),
  GhmcWard(code: 'W102', name: 'Boduppal', circle: 'LB Nagar'),
  GhmcWard(code: 'W103', name: 'Medipally', circle: 'LB Nagar'),
  GhmcWard(code: 'W104', name: 'Peerzadiguda', circle: 'LB Nagar'),
  GhmcWard(code: 'W105', name: 'Dammaiguda', circle: 'Secunderabad'),
  GhmcWard(code: 'W106', name: 'Annajiguda', circle: 'Secunderabad'),
  GhmcWard(code: 'W107', name: 'Yapral', circle: 'Secunderabad'),
  GhmcWard(code: 'W108', name: 'Petbasheerabad', circle: 'Secunderabad'),
  GhmcWard(code: 'W109', name: 'Medchal', circle: 'Secunderabad'),
  GhmcWard(code: 'W110', name: 'Kompally', circle: 'Secunderabad'),
  GhmcWard(code: 'W111', name: 'Dundigal', circle: 'Secunderabad'),
  GhmcWard(code: 'W112', name: 'Gajularamaram', circle: 'Serilingampally'),
  GhmcWard(code: 'W113', name: 'Pragathi Nagar', circle: 'Serilingampally'),
  GhmcWard(code: 'W114', name: 'Isnapur', circle: 'Serilingampally'),
  GhmcWard(code: 'W115', name: 'Patancheru', circle: 'Serilingampally'),
  GhmcWard(code: 'W116', name: 'Sangareddy', circle: 'Serilingampally'),
  GhmcWard(code: 'W117', name: 'Medak Road', circle: 'Serilingampally'),
  GhmcWard(code: 'W118', name: 'Shamshabad', circle: 'LB Nagar'),
  GhmcWard(code: 'W119', name: 'Rajiv Gandhi Intl Airport', circle: 'LB Nagar'),
  GhmcWard(code: 'W120', name: 'Balapur', circle: 'LB Nagar'),
  GhmcWard(code: 'W121', name: 'Bandlaguda Jagir', circle: 'LB Nagar'),
  GhmcWard(code: 'W122', name: 'Mansoorabad', circle: 'LB Nagar'),
  GhmcWard(code: 'W123', name: 'Pedda Amberpet', circle: 'LB Nagar'),
  GhmcWard(code: 'W124', name: 'Moinabad', circle: 'Khairatabad'),
  GhmcWard(code: 'W125', name: 'Shamirpet', circle: 'Secunderabad'),
  GhmcWard(code: 'W126', name: 'Keesara', circle: 'Secunderabad'),
  GhmcWard(code: 'W127', name: 'Ghatkesar', circle: 'LB Nagar'),
  GhmcWard(code: 'W128', name: 'Cherlapally', circle: 'LB Nagar'),
  GhmcWard(code: 'W129', name: 'Kushaiguda', circle: 'LB Nagar'),
  GhmcWard(code: 'W130', name: 'Habsiguda', circle: 'LB Nagar'),
  GhmcWard(code: 'W131', name: 'Vidyanagar Colony', circle: 'LB Nagar'),
  GhmcWard(code: 'W132', name: 'Mallapur', circle: 'LB Nagar'),
  GhmcWard(code: 'W133', name: 'Sainikpuri', circle: 'Secunderabad'),
  GhmcWard(code: 'W134', name: 'Malkajgiri Town', circle: 'Secunderabad'),
  GhmcWard(code: 'W135', name: 'Lothkunta', circle: 'Secunderabad'),
  GhmcWard(code: 'W136', name: 'Quthbullapur Village', circle: 'Serilingampally'),
  GhmcWard(code: 'W137', name: 'Ameerpet Junction', circle: 'Secunderabad'),
  GhmcWard(code: 'W138', name: 'West Marredpally', circle: 'Secunderabad'),
  GhmcWard(code: 'W139', name: 'East Marredpally', circle: 'Secunderabad'),
  GhmcWard(code: 'W140', name: 'Bolarum', circle: 'Secunderabad'),
  GhmcWard(code: 'W141', name: 'Secunderabad Cantonment', circle: 'Secunderabad'),
  GhmcWard(code: 'W142', name: 'Ramgopalpet', circle: 'Secunderabad'),
  GhmcWard(code: 'W143', name: 'James Street', circle: 'Secunderabad'),
  GhmcWard(code: 'W144', name: 'SD Road', circle: 'Secunderabad'),
  GhmcWard(code: 'W145', name: 'Paradise Circle', circle: 'Secunderabad'),
  GhmcWard(code: 'W146', name: 'Rasoolpura', circle: 'Secunderabad'),
  GhmcWard(code: 'W147', name: 'Mahankali', circle: 'Secunderabad'),
  GhmcWard(code: 'W148', name: 'Nallakunta', circle: 'Secunderabad'),
  GhmcWard(code: 'W149', name: 'Barkatpura', circle: 'Secunderabad'),
  GhmcWard(code: 'W150', name: 'Chapel Road', circle: 'Secunderabad'),
];
